import { COLORS, FONT_SIZES, SPACING } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const driverProfileStyles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.white,
    margin: SPACING.md,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  headerBanner: {
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    alignItems: 'center',
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.sm,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.6)',
  },
  heading: { fontSize: FONT_SIZES.lg, fontWeight: '700', color: COLORS.white },
  subheading: { fontSize: FONT_SIZES.sm, color: 'rgba(255,255,255,0.85)', marginTop: 2 },
  body: { padding: SPACING.lg },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    gap: SPACING.sm,
  },
  rowLast: { borderBottomWidth: 0 },
  rowIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowText: { flex: 1 },
  label: { fontSize: FONT_SIZES.sm - 1, color: COLORS.textSecondary },
  value: { fontSize: FONT_SIZES.md, color: COLORS.textPrimary, fontWeight: '600', marginTop: 1 },
  placeholder: { color: COLORS.textSecondary, fontStyle: 'italic', fontWeight: '400' },
  editHint: {
    textAlign: 'center',
    fontSize: FONT_SIZES.sm - 1,
    color: COLORS.primary,
    fontWeight: '600',
    marginTop: SPACING.md,
  },
  formBody: { padding: SPACING.lg, gap: SPACING.md },
  fieldGroup: { gap: 6 },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.background,
    gap: SPACING.xs,
  },
  input: {
    flex: 1,
    fontSize: FONT_SIZES.md,
    color: COLORS.textPrimary,
    paddingVertical: SPACING.sm,
  },
  buttonRow: { flexDirection: 'row', gap: SPACING.sm, marginTop: SPACING.sm },
  button: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: SPACING.sm,
    borderRadius: 12,
  },
  saveButton: { backgroundColor: COLORS.primary },
  cancelButton: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.border },
  buttonText: { fontWeight: '700', fontSize: FONT_SIZES.sm },
  saveButtonText: { color: COLORS.white },
  cancelButtonText: { color: COLORS.textSecondary },
});
